# Generated by Django 5.2.1 on 2025-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('publisher', models.CharField(max_length=255, verbose_name='Издательство')),
                ('year', models.PositiveIntegerField(verbose_name='Год издания')),
                ('page_count', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('age_limit', models.CharField(max_length=10, verbose_name='Возрастное ограничение')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('annotation', models.TextField(verbose_name='Аннотация')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Обложка')),
                ('text', models.TextField(verbose_name='Текст книги')),
            ],
        ),
    ]
